language: node_js
node_js:
- 4.0.0
deploy:
  provider: npm
  email: henleyedition@gmail.com
  api_key:
    secure: kwdAAWHxzl1l0wRrwgCwhqO55usa8Gd4/3tSY2pDYaeQrv/dmQM+VfTtoBkbM/7vCezG0gzCUxxd/wPDzE7C4IXGJlnuJTE+PN8tAt61L9Iyi0ezYuStBa5T3h1sZtznxdv4VZO46kNllJ41eMmrwiS5MrXWHxzufetb0qCBZUPSKmiz5TX08hKh65dsRuNxQntZxiE//K3nQohHPB5siMWHqFV41CO4p5dIJWQXnNrKCmC8MHO65dkjtPxTVquaOYEExpCk9zwun7zbMqq52OoeFNnmq3hZzzSoKdKnOtL1roLBYN5PYiXdsnCSAxRm0D+Op/WGC6Ke+x1iXbKHUICrvIsfn9qTZlmt//d5ar4UMql8TzhIzabS0Mdwq7rhkC5eV4L4UX7BZEu0KbbeiW3G2EGk3Ga7alvyvamlcVKFyAjtSnRDmlIMeFgoFc/s2fInY6f0cPZO4FZ4mrmEAJgMPxUlMx1ltZk93NRDocxIi3EcmYkFOr0r97hPyYE6dEyZ6P89ycmrvxLiYVxtMlx5dMc80+u2mSa3uMCvP48ylLSje+qf45xl6DRenLLah3xbjhp5Z+L4SXs3TeeZWYp0JNhk9fJsNuwLMvBl2AYcISuf17gGPoL42gBmpVJsfFJ1JdVM0fl8LZqL3PEvMMN0gYm8crPVXQZ6XlZimN0=
  on:
    tags: true
    all_branches: true
    repo: echenley/karma-chai-equal-jsx
cache:
  bundler: true
  directories:
  - node_modules
